### PR TITLE
Fix log-level flag support

### LINKED ISSUE #12: --log-level is a string flags
Hello.

`--log-level` is defined as a boolean option
https://github.com/docker/compose-switch/blob/9e07182c1408e8eedac863e9d10eb170e18e4eef/redirect/convert.go#L9-L24
It is not right. Thiis option takes string argument.
```
  --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
```
CC: @potiuk

Related issue: https://github.com/apache/airflow/pull/18725

### PR DESCRIPTION
**Pull request by ad-m**
close #12

### CODE REVIEW

File: redirect/convert_test.go [hunk 1]
```diff
@@ -63,6 +63,12 @@ func Test_convert(t *testing.T) {
 			args: []string{"exec", "mongo", "mongo", "--host", "mongo"},
 			want: []string{"compose", "exec", "mongo", "mongo", "--host", "mongo"}, // --host is passed to exec
 		},
+		{
+			name: "issues/12",
+			args: []string{"--log-level", "INFO", "up"},
+			want: []string{"--log-level", "INFO", "up"},
```
Comment (mik-laj) [inline redirect/convert_test.go:69]: Here, we should have `"--log-level", "INFO", "compose", "up"`
```
$ make test
go test -cover github.com/docker/compose-switch github.com/docker/compose-switch/exec github.com/docker/compose-switch/internal github.com/docker/compose-switch/redirect
?       github.com/docker/compose-switch        [no test files]
?       github.com/docker/compose-switch/exec   [no test files]
?       github.com/docker/compose-switch/internal       [no test files]
--- FAIL: Test_convert (0.00s)
    --- FAIL: Test_convert/issues/12 (0.00s)
        convert_test.go:76: assertion failed:
            --- tt.want
            +++ got
              []string{
                "--log-level",
                "INFO",
            +   "compose",
                "up",
              }

FAIL
coverage: 61.0% of statements
FAIL    github.com/docker/compose-switch/redirect       0.004s
FAIL
make: *** [Makefile:18: test] Error 1
```

**Review by mat007 — APPROVED** [review]
Makes sense, thanks!
